apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat-federate
  namespace: elastic-monitoring
spec:
  type: metricbeat
  version: 8.4.0
  elasticsearchRef:
    name: elasticsearch
  config:
    metricbeat:
      modules:
        - module: prometheus
          hosts: ["https://prometheus-k8s.openshift-monitoring.svc:9091"]
          metrics_path: '/federate'
          query:
            'match[]': '{job=~"cluster-.*"}'
          # Use service account based authorization:
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          ssl.certificate_authorities:
            - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  deployment:
    podTemplate:
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true
        containers:
          - args: ["-e","-c","/etc/beat.yml"]
            name: metricbeat
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
        volumes:
          - emptyDir: {}
            name: beat-data
